name: oncotarget-lite
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python
  - python=3.11
  - pip
  
  # Core scientific computing
  - numpy=1.24.*
  - pandas=2.0.*
  - scikit-learn=1.3.*
  - scipy=1.11.*
  
  # Machine Learning
  - pytorch::pytorch=2.0.*
  - pytorch::torchvision=0.15.*
  - lightgbm=4.0.*
  
  # Data processing
  - pyarrow=12.0.*
  - h5py=3.9.*
  - pytables=3.8.*
  
  # Configuration and experiment tracking  
  - pydantic=2.*
  - pyyaml=6.*
  - mlflow=2.5.*
  - omegaconf=2.3.*
  - hydra-core=1.3.*
  
  # Visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.15.*
  - streamlit
  
  # Statistics and modeling
  - statsmodels=0.14.*
  - lifelines=0.27.*
  
  # Utilities
  - tqdm=4.65.*
  - requests=2.31.*
  - joblib=1.3.*
  
  # Development tools
  - pytest=7.4.*
  - pytest-cov=4.1.*
  - black=23.7.*
  - ruff
  - mypy=1.4.*
  - pre-commit=3.3.*
  
  # Jupyter (optional)
  - jupyter=1.0.*
  - ipywidgets=8.0.*
  
  # Pip-only packages
  - pip:
      - shap==0.43.0
      - xgboost==1.7.6
      - typer==0.9.0
      - jinja2==3.1.2
      - playwright==1.39.0
      - biopython==1.81
      - gseapy==1.0.4
      - pycombat==0.3.3
      - torchmetrics
