n_estimators: {type: int, low: 50, high: 500}
max_depth: {type: int, low: 3, high: 10}
learning_rate: {type: loguniform, low: 0.0001, high: 0.3}
subsample: {type: uniform, low: 0.5, high: 1.0}
colsample_bytree: {type: uniform, low: 0.5, high: 1.0}

