import streamlit as st
import streamlit.components.v1 as components
from pathlib import Path

st.set_page_config(page_title="Monitoring Report", layout="wide")
st.title("📈 Monitoring Report")

st.markdown("""
This page displays the latest data drift and model performance monitoring report, generated by our automated monitoring pipeline.
This report is created by comparing the most recent production data against a reference dataset (e.g., the training data).
""")

# Path to the Evidently report
report_path = Path("reports/monitoring_report.html")

if report_path.exists():
    with open(report_path, 'r', encoding='utf-8') as f:
        html_content = f.read()
    
    st.subheader("Evidently Monitoring Dashboard")
    components.html(html_content, height=800, scrolling=True)
else:
    st.warning("Monitoring report not found. Please run the monitoring pipeline to generate the report.")






